apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: frappe
  namespace: flux-system
spec:
  interval: 1m
  url: <https://github.com/devqx/venco-devops-accessment>
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/manifests/
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: frappe
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./deplo/frappe
  prune: true
  sourceRef:
    kind: GitRepository
    name: frappe
  targetNamespace: frappe
