
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: venco-helm-repo
  namespace: flux-system
spec:
  interval: 1m0s
  url: <https://venco.github.io/helm-charts/>

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: frappe-venco
  namespace: dev
spec:
  chart:
    spec:
      chart: frappe
      sourceRef:
        kind: HelmRepository
        name: venco-helm-repo
				namespace: flux-system
      version: 0.1.0
  interval: 1m0s