{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "frappe.serviceAccountName" . }}
  labels:
{{ include "frappe.labels" . | indent 4 }}
{{- end -}}
